// This file is regenerated by scripts/build-wasm-inline.mjs after `tsc`.
// The empty strings here are placeholders so the TypeScript compiler is happy.
// The build script overwrites the emitted dist/core/wasm-data.js with the
// real base64 payloads.
export const GRAMMAR_WASM_BASE64 = "";
export const RUNTIME_WASM_BASE64 = "";
